// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SummerSchool.ApplicationSystems.Repository.Context;

#nullable disable

namespace SummerSchool.ApplicationSystems.Repository.Migrations
{
    [DbContext(typeof(MainDbContext))]
    partial class MainDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SummerSchool.ApplicationSystems.Core.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CODE");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DEPARTMENT");

                    b.Property<string>("Faculty")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("FACULTY");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ADDED_DATE");

                    b.Property<string>("InsertedUser")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ADDED_USER");

                    b.Property<int>("IsActive")
                        .HasColumnType("int")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NAME");

                    b.Property<int>("Quota")
                        .HasColumnType("int")
                        .HasColumnName("QUOTA");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATED_DATE");

                    b.Property<string>("UpdatedUser")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("UPDATED_USER");

                    b.HasKey("Id");

                    b.ToTable("COURSE", (string)null);
                });

            modelBuilder.Entity("SummerSchool.ApplicationSystems.Core.Entities.CourseApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<int>("ApplicationStatus")
                        .HasColumnType("int")
                        .HasColumnName("APPLICATION_STATUS");

                    b.Property<string>("ApplicationStatusDescription")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("APPLICATION_STATUS_DESCRIPTION");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("COURSE_ID");

                    b.Property<int>("IsActive")
                        .HasColumnType("int")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("STUDENT_ID");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATED_DATE");

                    b.Property<string>("UpdatedUser")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("UPDATED_USER");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId", "CourseId")
                        .IsUnique();

                    b.ToTable("COURSE_APPLICATION", (string)null);
                });

            modelBuilder.Entity("SummerSchool.ApplicationSystems.Core.Entities.OtpVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("CODE");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ADDED_DATE");

                    b.Property<int>("IsActive")
                        .HasColumnType("int")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PHONE_NUMBER");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber");

                    b.ToTable("OTP_VERIFICATION", (string)null);
                });

            modelBuilder.Entity("SummerSchool.ApplicationSystems.Core.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("COUNTRY_CODE");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DEPARTMENT");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Faculty")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("FACULTY");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("FIRST_NAME");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("IDENTITY_NUMBER");

                    b.Property<int>("IsActive")
                        .HasColumnType("int")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("LAST_NAME");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PHONE_NUMBER");

                    b.Property<string>("SchoolNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SCHOOL_NUMBER");

                    b.HasKey("Id");

                    b.ToTable("STUDENT", (string)null);
                });

            modelBuilder.Entity("SummerSchool.ApplicationSystems.Core.Entities.CourseApplication", b =>
                {
                    b.HasOne("SummerSchool.ApplicationSystems.Core.Entities.Course", "Course")
                        .WithMany("CourseApplications")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SummerSchool.ApplicationSystems.Core.Entities.Student", "Student")
                        .WithMany("CourseApplications")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SummerSchool.ApplicationSystems.Core.Entities.Course", b =>
                {
                    b.Navigation("CourseApplications");
                });

            modelBuilder.Entity("SummerSchool.ApplicationSystems.Core.Entities.Student", b =>
                {
                    b.Navigation("CourseApplications");
                });
#pragma warning restore 612, 618
        }
    }
}
